name: .NET + Docker CI Pipeline

on:
  workflow_dispatch:

jobs:
  build-dotnet:
    name: Build .NET Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore DevOpsFrontend/DevOpsFrontend.csproj

      - name: Build Application
        run: dotnet build DevOpsFrontend/DevOpsFrontend.csproj --configuration Release --no-restore

  docker-build-run:
    runs-on: ubuntu-latest
    needs: build-dotnet

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t devopsfrontend -f DevOpsFrontend/Dockerfile DevOpsFrontend

      - name: Run Container
        run: |
          docker run -d -p 8080:8080 --name test-container devopsfrontend
          sleep 10

      - name: Check Running Containers
        run: docker ps

      - name: Wait for App
        run: |
          for i in {1..10}; do
            curl -s http://localhost:8080 && break
            echo "Waiting for app..."
            sleep 5
          done

      - name: Show Logs
        run: docker logs test-container