name: .NET + Docker CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-dotnet:
    name: Build .NET Application
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: DevOpsFrontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Release --no-restore

  docker-build-run:
    name: Build and Run Docker Image
    runs-on: ubuntu-latest
    needs: build-dotnet

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t devopsfrontend -f DevOpsFrontend/Dockerfile DevOpsFrontend

      - name: Run Docker Container
        run: |
          docker run -d -p 8080:8080 --name test-container devopsfrontend

      - name: Wait For Application To Start
        run: |
          echo "Waiting for application..."
          for i in {1..10}; do
            if curl -s http://localhost:8080 > /dev/null; then
              echo "Application is up!"
              break
            fi
            echo "Still waiting..."
            sleep 5
          done

      - name: Show Frontend HTML Output
        run: curl http://localhost:8080

      - name: Show Container Logs
        run: docker logs test-container